### ISSUE TITLE
Payment with integer only

### ISSUE THREAD

**Issue by madtomic** [neolumia/vault#3]
Can you please add a check for if a player is paying with an integer and not a double. If a player tries to pay 1.5 or 1.04 then it would said, "You cannot pay that amount."

notIntenger: true/false //toggle option to enable this feature
paymentErrorMSG: "&cYou cannot pay that amount."

Thanks

**Comment by conreptio** [comment]
This is not a Vault issue.

An implementation should provide such feature, not the API.
